dubbo:
  application:
    name: dubbo-spring-boot-demo-consumer
    dump-enable: false
  protocol:
    name: tri
    port: -1
#    serialization: protobuf
  registry:
    address: zookeeper://${zookeeper.address:127.0.0.1}:2181
    timeout: 250000
    parameters:
      blockUntilConnectedWait: 2500
  config-center:
    timeout: 250000

zookeeper:
  address: 1.12.66.67


server:
  port: 8082
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher # 解决springboot和swagger2版本冲突