dubbo:
  application:
    name: dubbo-spring-boot-demo-provider
  protocol:
    name: tri
    port: -1
#    serialization: protobuf
  registry:
    address: zookeeper://${zookeeper.address:127.0.0.1}:2181
    timeout: 250000
    parameters:
      blockUntilConnectedWait: 2500
  config-center:
    timeout: 250000

zookeeper:
  address: 1.12.66.67

server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: 127.0.0.1
    db: dubbo
    url: jdbc:mysql://${spring.datasource.host}:3306/${spring.datasource.db}?serverTimezone=GMT%2b8
    username: root
    password: 9738faq